spring:
  application:
    name: server-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8714/eureka/
encrypt:
  key: 1234567890123456

server:
  port: 8888
